# Generated by Django 4.0.5 on 2022-06-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproduct',
            name='category',
        ),
    ]
