# Generated by Django 4.0.5 on 2022-07-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_featuredproduct_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCoruosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/home')),
                ('main_text', models.TextField(max_length=100)),
                ('sub_text', models.TextField(max_length=200)),
            ],
        ),
    ]
