# Generated by Django 4.0.5 on 2022-07-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_homecoruosel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeCoruosel',
            new_name='HomeCarousel',
        ),
    ]
