# Generated by Django 4.0.4 on 2022-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_homecoruosel_homecarousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.CharField(max_length=20)),
                ('discount_amount', models.ImageField(upload_to='')),
                ('coupon_code', models.CharField(max_length=20)),
            ],
        ),
    ]
