# Generated by Django 4.0.5 on 2022-06-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_orderproduct_color_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('New', 'New'), ('Completed', 'Completed')], default='New', max_length=10),
        ),
    ]
