# Generated by Django 4.0.4 on 2023-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('New', 'New'), ('Completed', 'Completed'), ('Accepted', 'Accepted')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('shipped', 'shipped'), ('Delivered', 'Delivered'), ('cancelled', 'cancelled')], default='new', max_length=10),
        ),
    ]
