# Generated by Django 4.0.4 on 2022-06-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartitem_variation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variation',
            new_name='variations',
        ),
    ]
