# Generated by Django 4.0.4 on 2022-07-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_coupons_delete_coupens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='coupon_code',
        ),
    ]
