# Generated by Django 4.0.4 on 2022-07-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_coupons_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='coupon_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
